JAVAC = javac

Colleen = Colleen.class

Grace = Grace.class

Colleen_src = Colleen.java

Grace_src = Grace.java

$(Colleen): $(Colleen_src)
	$(JAVAC) $^

$(Grace): $(Grace_src)
	$(JAVAC) $^

clean:

fclean:
	rm -rf $(Colleen) $(Grace) $(Sully)

re: